const USER_INFO_STORAGE_KEY = 'BONBONNIERE_USER_INFO_STORAGE';
const SIDER_COLLAPSED_STORAGE_KEY = 'BONBONNIERE_SIDER_COLLAPSED_STORAGE';
const API_URL = 'http://localhost:3002/api/1';
const API_REQUEST_TIMEOUT = 1000 * 60 * 15;
const DEFAULT_LOCALE = 'zh-CN';

export default {
  USER_INFO_STORAGE_KEY,
  SIDER_COLLAPSED_STORAGE_KEY,
  API_URL,
  API_REQUEST_TIMEOUT,
  DEFAULT_LOCALE
};
