const USER_INFO_STORAGE_KEY = 'BONBONNIERE_USER_INFO_STORAGE';
const SIDER_COLLAPSED_STORAGE_KEY = 'BONBONNIERE_SIDER_COLLAPSED_STORAGE';

export { USER_INFO_STORAGE_KEY, SIDER_COLLAPSED_STORAGE_KEY };
